In [3]:
!pip install pandasql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandasql in c:\users\burleigh\appdata\roaming\python\python310\site-packages (0.7.3)
Requirement already satisfied: numpy in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from pandasql) (1.22.3)
Requirement already satisfied: pandas in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from pandasql) (1.4.2)
Requirement already satisfied: sqlalchemy in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from pandasql) (1.4.36)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from pandas->pandasql) (2022.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from sqlalchemy->pandasql) (1.1.2)
Requirement already satisfied: six>=1.5 in c:\users\burleigh\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)

WARNING: There was an error checking the latest version of pip.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandasql import sqldf
pysqldf = lambda q : sqldf(q, globals())

In [5]:
import time
def strptime(timestr):
    return time.mktime(time.strptime(timestr, "%Y-%m-%d"))
def strftime(timesec):
    return time.strftime("%Y-%m-%d", time.time(timesec))

In [6]:
sentimentdf = pd.read_csv('ticker_data.csv')
stockdf = pd.read_csv('stock_data.csv')

In [7]:
query = "SELECT ticker, date, SUM(compound) AS netcompound "\
        "FROM sentimentdf AS sent "\
        "GROUP BY sent.ticker, sent.date"

In [8]:
datadf = pysqldf(query)

In [9]:
datadf

     ticker        date  netcompound
0        AA  2021-07-01       0.4871
1      AAPL  2021-04-28       0.9051
2      AAPL  2021-06-17       1.8809
3      AAPL  2021-07-24       0.7238
4      AAPL  2021-08-13       5.9172
...     ...         ...          ...
2583    ZIM  2022-03-15       0.1829
2584     ZM  2021-11-24       6.8544
2585   ZNGA  2021-06-28      -0.9735
2586   ZNGA  2021-09-16       0.7833
2587   ZNGA  2022-01-07       0.4019

[2588 rows x 3 columns]

In [10]:
mentions = [(ticker, len(datadf[datadf['ticker']==ticker])) for ticker in set(datadf['ticker'])]
mentions.sort(key=lambda x : x[1], reverse=True)

In [11]:
mentions

[('DD', 111),
 ('CLF', 100),
 ('GME', 97),
 ('SPY', 89),
 ('SI', 73),
 ('OI', 68),
 ('GOEV', 54),
 ('RKT', 54),
 ('PM', 52),
 ('TSLA', 52),
 ('T', 49),
 ('IMO', 48),
 ('MT', 48),
 ('SG', 44),
 ('CLVS', 40),
 ('AMC', 37),
 ('S', 33),
 ('IRNT', 30),
 ('C', 28),
 ('AAPL', 27),
 ('USA', 25),
 ('U', 25),
 ('OCGN', 24),
 ('CLOV', 21),
 ('PLBY', 18),
 ('ET', 18),
 ('MSFT', 16),
 ('BBIG', 16),
 ('F', 16),
 ('DWAC', 16),
 ('E', 15),
 ('EDIT', 15),
 ('FOMC', 15),
 ('D', 14),
 ('ESSC', 12),
 ('MRNA', 12),
 ('BAC', 12),
 ('ATER', 12),
 ('BB', 11),
 ('CLNE', 11),
 ('CRTX', 11),
 ('IBKR', 11),
 ('SOFI', 11),
 ('OPAD', 11),
 ('CBOE', 11),
 ('X', 11),
 ('ATOS', 11),
 ('LNG', 10),
 ('TA', 10),
 ('NEGG', 10),
 ('JPM', 10),
 ('PAYA', 9),
 ('CC', 9),
 ('K', 9),
 ('PLTR', 9),
 ('GS', 9),
 ('WEBR', 8),
 ('UWMC', 8),
 ('NUE', 8),
 ('GENI', 8),
 ('MVIS', 8),
 ('APP', 8),
 ('AMZN', 8),
 ('DTE', 8),
 ('R', 7),
 ('OTRK', 7),
 ('SO', 7),
 ('VXX', 7),
 ('ZIM', 7),
 ('QQQ', 7),
 ('FB', 7),
 ('AM', 7),
 ('MARA', 7),
 ('TMC', 7),
 ('VXRT', 6),
 ('GREE', 6),
 ('NVAX', 6),
 ('SAVA', 6),
 ('GGPI', 6),
 ('LUMN', 6),
 ('IS', 6),
 ('NVDA', 6),
 ('SP', 6),
 ('RKLB', 6),
 ('ANY', 6),
 ('LOTZ', 6),
 ('UK', 6),
 ('RIDE', 6),
 ('MA', 6),
 ('TD', 6),
 ('HOOD', 6),
 ('M', 6),
 ('LYB', 6),
 ('MVST', 6),
 ('B', 6),
 ('ML', 5),
 ('TX', 5),
 ('PROG', 5),
 ('NFLX', 5),
 ('RSI', 5),
 ('PSTH', 5),
 ('BKKT', 5),
 ('SST', 5),
 ('PBT', 5),
 ('BGFV', 5),
 ('BKSY', 5),
 ('SPCE', 5),
 ('HGEN', 5),
 ('IONQ', 5),
 ('WWE', 5),
 ('BBAI', 4),
 ('BTBT', 4),
 ('OG', 4),
 ('AMD', 4),
 ('SLB', 4),
 ('IR', 4),
 ('PTON', 4),
 ('SENS', 4),
 ('BMTX', 4),
 ('TTCF', 4),
 ('ZEV', 4),
 ('BNTX', 4),
 ('DIS', 4),
 ('WMT', 4),
 ('PFE', 4),
 ('WKHS', 4),
 ('ARMK', 4),
 ('BA', 3),
 ('BABA', 3),
 ('TEAM', 3),
 ('FT', 3),
 ('BRCC', 3),
 ('APPH', 3),
 ('XOM', 3),
 ('LMAO', 3),
 ('RBAC', 3),
 ('APRN', 3),
 ('BE', 3),
 ('SA', 3),
 ('CCJ', 3),
 ('NMRD', 3),
 ('RENN', 3),
 ('OR', 3),
 ('GO', 3),
 ('LCID', 3),
 ('GWH', 3),
 ('OPFI', 3),
 ('RIVN', 3),
 ('MGI', 3),
 ('O', 3),
 ('PIPP', 3),
 ('ZNGA', 3),
 ('BTO', 3),
 ('WDC', 3),
 ('TLRY', 3),
 ('PG', 3),
 ('MU', 3),
 ('NOW', 3),
 ('AHPI', 3),
 ('L', 3),
 ('TV', 3),
 ('NXE', 3),
 ('GSAT', 3),
 ('CEI', 3),
 ('NET', 3),
 ('UVXY', 3),
 ('AG', 3),
 ('ARQQ', 3),
 ('SHO', 3),
 ('SPIR', 3),
 ('GRAB', 3),
 ('GOED', 3),
 ('BMY', 3),
 ('TWTR', 3),
 ('STEM', 3),
 ('NOK', 3),
 ('VLTA', 3),
 ('COIN', 3),
 ('MNMD', 2),
 ('FCX', 2),
 ('LZB', 2),
 ('FAST', 2),
 ('CYRN', 2),
 ('SBUX', 2),
 ('DLTR', 2),
 ('DOCU', 2),
 ('J', 2),
 ('ME', 2),
 ('EOD', 2),
 ('DASH', 2),
 ('USO', 2),
 ('CB', 2),
 ('WH', 2),
 ('VIXY', 2),
 ('H', 2),
 ('SMM', 2),
 ('RH', 2),
 ('GNPX', 2),
 ('IT', 2),
 ('ISPO', 2),
 ('CP', 2),
 ('DE', 2),
 ('MSTR', 2),
 ('PXLW', 2),
 ('ALL', 2),
 ('REAL', 2),
 ('LEAP', 2),
 ('AEO', 2),
 ('PSLV', 2),
 ('BMO', 2),
 ('ASTS', 2),
 ('LGVN', 2),
 ('MMAT', 2),
 ('HSBC', 2),
 ('ALPP', 2),
 ('ST', 2),
 ('TELL', 2),
 ('API', 2),
 ('CVS', 2),
 ('APPS', 2),
 ('IP', 2),
 ('MO', 2),
 ('GLD', 2),
 ('GGB', 2),
 ('PTRA', 2),
 ('BGS', 2),
 ('SE', 2),
 ('MSM', 2),
 ('SNDL', 2),
 ('WEAT', 2),
 ('IBM', 2),
 ('ISPOW', 2),
 ('LULU', 2),
 ('TSM', 2),
 ('SDC', 2),
 ('PT', 2),
 ('RMED', 2),
 ('FF', 2),
 ('DM', 2),
 ('PRDS', 2),
 ('MD', 2),
 ('WOW', 2),
 ('ASAN', 2),
 ('BRPM', 2),
 ('DBA', 2),
 ('PQEFF', 2),
 ('AEYE', 2),
 ('RDW', 2),
 ('OTLY', 2),
 ('JNJ', 2),
 ('GOOGL', 2),
 ('CVM', 2),
 ('III', 2),
 ('TM', 2),
 ('DNA', 2),
 ('ABNB', 2),
 ('PSA', 2),
 ('TOST', 2),
 ('VALE', 2),
 ('CPNG', 2),
 ('COST', 2),
 ('SKLZ', 2),
 ('TWNK', 2),
 ('UPS', 2),
 ('BTTX', 2),
 ('CSCO', 1),
 ('OXM', 1),
 ('NVEI', 1),
 ('BZFD', 1),
 ('NTLA', 1),
 ('CF', 1),
 ('RHI', 1),
 ('PROF', 1),
 ('LMND', 1),
 ('DIDI', 1),
 ('LVS', 1),
 ('DISH', 1),
 ('WTI', 1),
 ('MNDY', 1),
 ('JD', 1),
 ('AL', 1),
 ('PDS', 1),
 ('SBLK', 1),
 ('DKNG', 1),
 ('RA', 1),
 ('GL', 1),
 ('PTR', 1),
 ('LFLY', 1),
 ('KHC', 1),
 ('CZR', 1),
 ('LSPD', 1),
 ('AUPH', 1),
 ('SATL', 1),
 ('UVIX', 1),
 ('QLGN', 1),
 ('BLK', 1),
 ('SHPW', 1),
 ('OWL', 1),
 ('CS', 1),
 ('CORN', 1),
 ('VLN', 1),
 ('LUV', 1),
 ('LMT', 1),
 ('GEO', 1),
 ('DGX', 1),
 ('NG', 1),
 ('DT', 1),
 ('BENE', 1),
 ('RBLX', 1),
 ('ICE', 1),
 ('AAWW', 1),
 ('GP', 1),
 ('LEN', 1),
 ('AMRK', 1),
 ('UUUU', 1),
 ('OP', 1),
 ('Y', 1),
 ('ZI', 1),
 ('BTX', 1),
 ('CRSR', 1),
 ('IMPP', 1),
 ('CPE', 1),
 ('HR', 1),
 ('DBO', 1),
 ('GROM', 1),
 ('UPST', 1),
 ('THCA', 1),
 ('UBS', 1),
 ('HL', 1),
 ('GOLD', 1),
 ('SMP', 1),
 ('CCXI', 1),
 ('ALLG', 1),
 ('ULTA', 1),
 ('PD', 1),
 ('TPST', 1),
 ('PATH', 1),
 ('PHAS', 1),
 ('SLV', 1),
 ('BEKE', 1),
 ('CIFR', 1),
 ('POSH', 1),
 ('GIS', 1),
 ('UE', 1),
 ('W', 1),
 ('VZ', 1),
 ('EXPR', 1),
 ('PUBM', 1),
 ('BTCM', 1),
 ('GSK', 1),
 ('HE', 1),
 ('SF', 1),
 ('XXII', 1),
 ('ALOT', 1),
 ('ARE', 1),
 ('HUT', 1),
 ('KAI', 1),
 ('ARCE', 1),
 ('BMBL', 1),
 ('MF', 1),
 ('EFTR', 1),
 ('WE', 1),
 ('GLG', 1),
 ('AUR', 1),
 ('VBIV', 1),
 ('APTV', 1),
 ('VRTX', 1),
 ('VTNR', 1),
 ('TRUE', 1),
 ('RFP', 1),
 ('MHK', 1),
 ('ROKU', 1),
 ('AMAT', 1),
 ('EVTL', 1),
 ('WTTR', 1),
 ('RDBX', 1),
 ('BYND', 1),
 ('CROX', 1),
 ('JP', 1),
 ('SBR', 1),
 ('MNTS', 1),
 ('KBH', 1),
 ('MAXR', 1),
 ('OWLT', 1),
 ('SQ', 1),
 ('BBBY', 1),
 ('CAKE', 1),
 ('DOCS', 1),
 ('ADBE', 1),
 ('LIDR', 1),
 ('ASO', 1),
 ('AGM', 1),
 ('TKAT', 1),
 ('ENPH', 1),
 ('ANGH', 1),
 ('KNX', 1),
 ('DG', 1),
 ('VEON', 1),
 ('AVCT', 1),
 ('DTC', 1),
 ('LOCL', 1),
 ('FCF', 1),
 ('UONE', 1),
 ('AFCG', 1),
 ('AMKR', 1),
 ('IQ', 1),
 ('ASM', 1),
 ('AEHL', 1),
 ('LEV', 1),
 ('LAUR', 1),
 ('WLL', 1),
 ('BEST', 1),
 ('PYPL', 1),
 ('KO', 1),
 ('BLNK', 1),
 ('NEO', 1),
 ('CRWD', 1),
 ('CND', 1),
 ('GB', 1),
 ('UROY', 1),
 ('RETA', 1),
 ('MET', 1),
 ('IPOF', 1),
 ('CYBN', 1),
 ('PL', 1),
 ('AI', 1),
 ('NI', 1),
 ('KKR', 1),
 ('VIRT', 1),
 ('POOL', 1),
 ('ELY', 1),
 ('REG', 1),
 ('AEI', 1),
 ('DDS', 1),
 ('WSM', 1),
 ('CANO', 1),
 ('BROS', 1),
 ('CFVI', 1),
 ('STC', 1),
 ('FATE', 1),
 ('COOP', 1),
 ('FATH', 1),
 ('ITUB', 1),
 ('GM', 1),
 ('COUP', 1),
 ('IRS', 1),
 ('TFSA', 1),
 ('MKD', 1),
 ('BX', 1),
 ('AA', 1),
 ('PHUN', 1),
 ('SRPT', 1),
 ('AMN', 1),
 ('TTD', 1),
 ('RAIL', 1),
 ('SR', 1),
 ('PSTG', 1),
 ('CISO', 1),
 ('CCTC', 1),
 ('GNRC', 1),
 ('BK', 1),
 ('KIND', 1),
 ('NWBO', 1),
 ('HVT', 1),
 ('JACK', 1),
 ('KR', 1),
 ('OXY', 1),
 ('WOOF', 1),
 ('QCOM', 1),
 ('DOW', 1),
 ('OCC', 1),
 ('HUGE', 1),
 ('CVX', 1),
 ('QS', 1),
 ('ZM', 1),
 ('SUNL', 1),
 ('AFRM', 1),
 ('MOVE', 1),
 ('EDSA', 1),
 ('COO', 1),
 ('CRVS', 1),
 ('PODD', 1),
 ('SHOP', 1),
 ('BKE', 1),
 ('MRIN', 1),
 ('CVNA', 1),
 ('CAR', 1),
 ('BBY', 1),
 ('YOU', 1),
 ('BC', 1),
 ('KMX', 1),
 ('ES', 1),
 ('MCD', 1),
 ('POST', 1),
 ('ASML', 1),
 ('WEN', 1),
 ('CAT', 1),
 ('LILM', 1),
 ('ETA', 1),
 ('SID', 1),
 ('CENN', 1),
 ('MSCI', 1),
 ('LAC', 1)]

In [12]:
datadf[datadf['ticker']=='DD']

    ticker        date  netcompound
602     DD  2021-04-22       0.9359
603     DD  2021-04-24       5.7991
604     DD  2021-04-26       2.1827
605     DD  2021-04-27       3.2789
606     DD  2021-04-28       5.6082
..     ...         ...          ...
708     DD  2022-04-15       1.8822
709     DD  2022-04-19       3.4468
710     DD  2022-04-23       0.2194
711     DD  2022-04-25       0.8741
712     DD  2022-04-27       2.1571

[111 rows x 3 columns]

In [ ]:
#plot both on same graph
#cross corelations plot
#plot against each other
#todo
#add in price change between days
#forward fill compound data a